### PR TITLE
Get rid of JSON Pointers

### LINKED ISSUE #13: health check is in webconcepts, too
i notices health check is listed as `custom`. if you're interested, at http://webconcepts.info/specs/IETF/I-D/inadarei-api-health-check it is listed at webconcepts, too.

### PR DESCRIPTION
**Pull request by philsturgeon**
Closes #13 & #14

### CODE REVIEW

**Comment by philsturgeon** [comment]
Getting `No data found for $..['RFC']..['6573']` and I dont have time to fix this right now.

**Comment by philsturgeon** [comment]
This is a huge blocker from this project, happy to throw some money at whoever gets it done. My brain hurts when I piss around with complex data structures, I want to get back to writing about API Gateways and Server-side validation.

**Comment by philsturgeon** [comment]
@matthewtrask can you maybe have a go?

**Comment by matthewtrask** [comment]
@philsturgeon looking at this  over the weekend

**Comment by philsturgeon** [comment]
@matthewtrask you're off the hook! Injured phil fixed things. Ride all the bikes for me!!

**Pull request merged**
